feat: POST /tasks/doneのAPI実装[WIP]
CATechAccel/hack-ios-server pull request #16
Opened 2021-03-28 01:45 UTC by hiroki90

POST /tasks/doneに対して
- 指定されたtaskIDをdone状態に変更
- 変更したtaskの配列をjsonで返す

を行うAPIの実装です
(WIP)

2021-03-30 06:13 UTC, k-ueki commented on pkg/infrastructure/task.go
> +	}
[imo] 複数変換するメソッド生やす方がスマートに見えるかも

2021-03-30 07:12 UTC, k-ueki commented
挙動チェックできてる？handler書き変わってなさそうだけど

2021-03-30 07:34 UTC, k-ueki requested changes

2021-03-30 07:34 UTC, k-ueki commented on pkg/infrastructure/task.go
> +	if err := tr.Conn.WithContext(ctx).Where("task_id IN ?", taskIDs).Updates(map[string]interface{}{"is_done": 1}).Error; err != nil {
[must] table指定漏れとtask_idというカラムはなさそう

2021-03-30 07:34 UTC, k-ueki commented on pkg/infrastructure/task.go
> +	if err := tr.Conn.WithContext(ctx).Where("task_id IN ?", taskIDs).Find(&ts).Error; err != nil {
[must] ここもtable指定漏れとtask_idというカラムはなさそう

2021-03-30 07:34 UTC, k-ueki commented on pkg/presentation/controller/task.go
> +}
返すものが決まってるなら、entityからresponseを生成するconverterも要るね

2021-04-11 14:44 UTC, hiroki90 commented
動作確認
- docker-composeで立ち上げた環境で確認
- taskを複数POST
- 下記curlコマンドを叩き，phpmyadmin上で該当するtaskのis_doneが0から1に更新されたことを確認（$taskID$には生成したtaskのidをそれぞれ挿入）
```shell
$ curl -X POST "http://localhost:8080/tasks/done" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"taskIDs\":[\"$taskID(1)$\",\""$taskID(2)$\"]}"
```
- 返り値
```
{"tasks":[{"id":"$taskID(1)$","name":"test","description":"test","isDone":true},{"id":"$taskID(2)$","name":"testtest","description":"testtest","isDone":true}]}
```

2021-04-11 16:20 UTC, BambooTuna commented on pkg/infrastructure/task.go
>  	ts := make([]*Task, 0, len(taskIDs))
予めメモリ確保してるのいいね！

2021-04-11 16:21 UTC, BambooTuna approved these changes
全体的に良さそう！

2021-04-12 06:59 UTC, ari1021 reviewed
全体的に良さそうです！

2021-04-12 06:59 UTC, ari1021 commented on pkg/presentation/controller/task.go
>  }
[imo] RequestとResponseの接頭語は同じ言葉にした方が対応関係がわかりやすそう(HogeRequestとHogeResponseみたいな感じ)

2021-04-12 06:59 UTC, ari1021 commented on pkg/infrastructure/task.go
> +	}
[imo] infrastructureの1関数の中に2つのDB操作が入っているのが個人的にはあまり良くないのかなと思います．ロジックの組み合わせはapplicationレイヤの責務だと思っています(わからん)

2021-04-12 11:56 UTC, k-ueki approved these changes
LGTM！

2021-04-13 17:51 UTC, krtsato reviewed
[imo]
DB の準備ができてからサーバ起動する法が良いかも。
docker-compose up で MySQL が立ち上がる前に server が DB コネクション作ろうとするとエラーになるため。
参考: https://docs.docker.com/compose/startup-order/

2021-04-13 18:08 UTC, krtsato commented
同じく全体的には LGTM です！

2021-04-15 13:22 UTC, hiroki90 commented on pkg/infrastructure/task.go
> +	}
たしかに...と思いました！
DB操作切り分けてみます！

2021-04-15 14:55 UTC, hiroki90 commented
コメントいただいた部分全て修正できたと思います！

- 前回と同じ方法で動作確認済です．

- ログで，mysqlの準備が完了してからサーバが起動しているのも確認しました．

大丈夫そうであればマージお願い致します！

2021-04-15 18:44 UTC, krtsato commented
LGTM！
皆さんから特になければ今日の昼間にマージします。

---

起動待機を [wait-for-it](https://github.com/vishnubob/wait-for-it) の nc コマンドで行なう場合
[dev.dockerfile の mysql-client](https://github.com/CATechAccel/hack-ios-server/blob/feature/dev-task-done/dev.dockerfile#L9) は不要になりそうだね。

コンテナ内に MySQL 環境を閉じたい場合
[この記事](https://qiita.com/MuuKojima/items/46496d458cff84423f2a) を参考に。

どちらでも良いと思います。

2021-04-16 03:08 UTC, merged