userに関するAPIの機能追加(DB操作，jwt)
CATechAccel/hack-ios-server pull request #5
Opened 2021-03-11 10:44 UTC by ari1021

**このPRは，現在developにあるモックAPIについてのcommitをmainにmergeした後にmergeします**

```
POST /users
POST /login

GET /restricted (このAPIを使う予定はありませんが，jwtの認証ができているかの確認のため残してあります)
```
について，db操作を行い，jwtのtoken作成を行うようにしました．

特に以下のポイントについてレビューをお願いします．
- [アーキテクチャ](https://github.com/CATechAccel/hack-ios-server/blob/main/docs/architecture.md)に沿った責務の切り分けができていますか？
- jwtの作成や認証についてダメな部分はありませんか？

2021-03-11 17:12 UTC, ari1021 commented on pkg/application/user.go
> +	}
(DDDっぽく)`*jwt.Token`のドメインモデルを定義して，そのmethodとして操作した方が良さそうですか？

```go
type token struct{
	jwt jwt.Token
}

func (t *token) SetClaim(key string, value interface{}) {
	claims := t.jwt.Claims.(jwt.MapClaims)
	claims[key] = value
}

func (t *token) Sign() (string, error) {
	signedToken, err := t.jwt.SignedString([]byte("secret"))
	if err != nil {
		return "", err
	}
	return signedToken, nil
}
```

2021-03-14 16:23 UTC, Khmer495 commented on pkg/application/user.go
> +	}
そっちのほうがCreateUserの動作の可読性があがるのでそうしてもいいかもね！
ただSetClaimとSignが必ずセットで用いられるのなら、最終形のtokenを返す関数として切り出すだけでも十分かも

2021-03-14 16:23 UTC, Khmer495 commented on pkg/application/user.go
> +	}
78~86行目と同じなので共通化したい

2021-03-14 16:23 UTC, Khmer495 commented on pkg/application/user.go
> +
User操作の間にUUIDがいてややこしいので、Userの上か下にコードの場所を移動したい
もしくはuuid.goを作ってもいいかも（1ファイル1interfaceの方が可読性が高そう）

2021-03-14 16:23 UTC, Khmer495 commented on pkg/infrastructure/user.go
> +}
updateAtとdeletedAtは不要？

2021-03-14 16:23 UTC, Khmer495 commented on pkg/infrastructure/user.go
> +	Password  string    `gorm:"size:255;uniqueIndex:uq_users_00;not null"`
nameとpassで複合ユニークキーにしてる理由ある？
nameがログインID的な扱いならname単体のユニークキーでよさそうだし、ニックネームなら重複を許しても良さそうだと思ったので

2021-03-15 02:51 UTC, ucpr requested changes
遅くなりました！:pray:

2021-03-15 02:51 UTC, ucpr commented on pkg/infrastructure/user.go
> +	user := NewUser(userID, userName, password)
passwordはhash化してDBにinsertした方が良さそうです！

- https://liginc.co.jp/377191
- https://qiita.com/anfangd/items/ea42a0f21e717ba8af2e

2021-03-15 02:51 UTC, ucpr commented on pkg/application/user.go
> +
ファイル分けた方がいいかな〜って個人的には思った！

2021-03-15 13:00 UTC, ari1021 commented on pkg/infrastructure/user.go
> +	user := NewUser(userID, userName, password)
1. クライアント側でhashしたパスワード(①とする)を送る
2. サーバ側はクライアントから受け取った①にsaltを加えてさらにhash化する
みたいなイメージであっていますか？

2021-03-15 13:01 UTC, ari1021 commented on pkg/infrastructure/user.go
> +	Password  string    `gorm:"size:255;uniqueIndex:uq_users_00;not null"`
nameはログインID的な扱いをしているので，name単体のユニークキーに変更します！

2021-03-15 13:01 UTC, ari1021 commented on pkg/infrastructure/user.go
> +}
必要ないと思っていたのですが，どのようなタイミングで必要になりそうですか？

2021-03-15 13:04 UTC, ari1021 commented on pkg/application/user.go
> +	}
SetClaimが呼ばれる回数みたいなものは可変にしたいので，別々のメソッドにしておこうと思います！

2021-03-15 13:19 UTC, ari1021 commented on pkg/application/user.go
> +	}
https://github.com/CATechAccel/hack-ios-server/pull/5/commits/5d682f29a57755ebe7e5f34bf745a349b114cee9
で修正しました！

2021-03-15 13:27 UTC, ari1021 commented on pkg/application/user.go
> +
https://github.com/CATechAccel/hack-ios-server/pull/5/commits/4835c2da8b371a2a5e50ba2cac6de18c1bc25a93
ここで修正しました！

2021-03-15 13:31 UTC, ari1021 commented on pkg/infrastructure/user.go
> +	Password  string    `gorm:"size:255;uniqueIndex:uq_users_00;not null"`
https://github.com/CATechAccel/hack-ios-server/pull/5/commits/514386bd5a2dbf4aa8860abbaada6313edbb4605
ここで修正しました！

2021-03-15 14:05 UTC, ari1021 commented on pkg/infrastructure/user.go
> +	user := NewUser(userID, userName, password)
https://github.com/CATechAccel/hack-ios-server/pull/5/commits/89a3045634dd808ad1ed86c1e870771aa25e70ae
ここで修正したような形で大丈夫そうですか？

2021-03-15 14:37 UTC, Khmer495 commented on pkg/application/user.go
> +
uuidはuserパッケージのままでもいいと思うが、そこはお好きに！

2021-03-15 15:02 UTC, Khmer495 commented on pkg/infrastructure/user.go
> +}
updateはパスワード変更時とか
deleteは論理削除してログインできないようにするときとかかな？

2021-03-16 01:50 UTC, ucpr commented on pkg/infrastructure/user.go
> +	user := NewUser(userID, userName, password)
>クライアント側でhashしたパスワード(①とする)を送る
>サーバ側はクライアントから受け取った①にsaltを加えてさらにhash化する
>みたいなイメージであっていますか？

で良いと思います！:+1:

2021-03-16 07:09 UTC, ari1021 commented on pkg/infrastructure/user.go
> +}
https://github.com/CATechAccel/hack-ios-server/pull/5/commits/d54881f739c38d9218ee02aba85cd5114d44de66
あってもいいかなと思ったのでここで追加しました！

2021-03-17 01:23 UTC, Khmer495 approved these changes
lgtm

2021-03-21 08:15 UTC, ucpr approved these changes

2021-03-21 10:07 UTC, merged