feat: docker-composeの追加
CATechAccel/hack-ios-server pull request #8
Opened 2021-03-15 04:13 UTC by hiroki90

docker-compose.ymlとdb/init/ddl.sqlを追加しました．

- docker-compose.ymlの書き方はあっていますでしょうか？

- ddl.sqlの書き方はあっていますでしょうか？

ご確認よろしくお願いしますmm

2021-03-17 00:34 UTC, krtsato requested changes

2021-03-17 00:34 UTC, krtsato commented on docker-compose.yml
> +      - 127.0.0.1:3000:8080
port 指定の仕方だけど
ここだけホストマシンの `127.0.0.1` を記述してるのはどうしてかな？
他の port と書き方を統一しておくと良いと思う。

2021-03-17 00:53 UTC, krtsato requested changes

2021-03-17 00:53 UTC, krtsato commented on docker-compose.yml
> +      - db-data:/var/lib/mysql
volumes に `db-data` という名前付き volumes を指定したときは
docker-compose のトップレベル (yml でいちばん上の階層) に同じく volumes セクションを定義する必要があるよ。
そのセクションで `db-data` を指定します。

```yml
volumes: # トップレベル
  db-data:
```

出てきたエラー ↓
```sh
% docker-compose up --build

ERROR: Named volume "db-data:/var/lib/mysql:rw" is used in service "mysql" but no declaration was found in the volumes section.
```

2021-03-17 00:53 UTC, krtsato commented on docker-compose.yml
> +version: "3"
version これでも良いけど
`3.8` とかマイナーバージョンまで指定すると良いと個人的には思ってます。
docker-compose に限らず暗黙のうちに update で環境変わっちゃうのを避けるため。

2021-03-17 00:55 UTC, krtsato commented on db/init/ddl.sql
> +-- MySQL Script generated by MySQL Workbench
SQL はパット見よさそうだけど
docker-compose の起動がうまくいってから確認します。

2021-03-18 12:48 UTC, hiroki90 commented on docker-compose.yml
> +      - 127.0.0.1:3000:8080
見様見真似でやっていたのでよくわかっていませんでした！
3000:8080
だけに修正します！

2021-03-18 16:56 UTC, krtsato requested changes

2021-03-18 16:56 UTC, krtsato commented on docker-compose.yml
> +      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
ここ my.conf 追加し忘れかな？
昨日の[ファイル](https://gist.github.com/krtsato/fdf46e14bbaf2faefc86547912147584)を参考に追加・動作確認・push よろしくです〜

ちなみに設定ファイル内の `[mysqld]` で `character-set-server` や `collation-server` とか指定してる場合
9 行目 `command` のオプション `--character-set-server=utf8 --collation-server=utf8_unicode_ci` は不要b

2021-03-18 16:57 UTC, krtsato commented on docker-compose.yml
> +    driver: local
丁寧なの良いね！
(local デフォルトなので指定しなくても OK だけど, 明示してくれると読む側は助かる)

2021-03-19 03:46 UTC, krtsato commented on db/init/ddl.sql
> +CREATE SCHEMA IF NOT EXISTS  `hack-ios-server_api` DEFAULT CHARACTER SET utf8mb4 ;
ちょっと細かいけど, アンダースコアかハイフンに統一するのが一般的だね。
特にDB 系はアンダースコアが主流だと思う。
なので `hack_ios_server_api` にできると 💯  ！

2021-03-19 04:07 UTC, Khmer495 reviewed
突然外部からコメント失礼します
docker-composeについて、おそらくapiサーバーの起動も必要？

2021-03-19 05:18 UTC, ari1021 commented on db/init/ddl.sql
> +CREATE TABLE IF NOT EXISTS `user` (
あらかじめ擦り合わせておかなかった僕が悪いんだけど，テーブル名は複数形でいきたい！   
`user` -> `users`

2021-03-19 05:22 UTC, ari1021 requested changes

2021-03-19 05:22 UTC, ari1021 commented on db/init/ddl.sql
> +    `name` VARCHAR(64) NOT NULL COMMENT 'ユーザ名',
jwtを使うので`auth_token`を保持する必要はなくて，  
`created_at`，`updated_at`，`deleted_at`を追加してほしい！  
詳しくは [ここ](https://github.com/CATechAccel/hack-ios-server/blob/feature/user/pkg/infrastructure/user.go) を見てほしい！  
(そもそもgormがmigrationをやってくれるのでddlが必要なのか問題はあるけど．．．)

2021-03-21 08:11 UTC, hiroki90 commented on db/init/ddl.sql
> +    `name` VARCHAR(64) NOT NULL COMMENT 'ユーザ名',
pkg/infrastructure/conn.goの中で自動でmigrationをやってくれてるのか！
ddlファイル無しでテーブルが作成できるから，ddlファイルは消して問題ないってことであってるかな？

2021-03-25 17:15 UTC, krtsato requested changes

2021-03-25 17:15 UTC, krtsato commented on docker-compose.yml
> +    env_file: ./configs/server.env
現在 server.env は空だから設定ないのと同じですね。こういう場合は env_file 書かなくていいよ。

2021-03-25 17:15 UTC, krtsato commented on server.dockerfile
> +  && curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin \
air をインストールしてますね。インストールしただけで使わないのかな？
使わない場合はこの行を削除しましょう。
Docker イメージのサイズが無為に大きくなりビルド時間が伸びて良いことがないので。

2021-03-25 17:39 UTC, krtsato commented on db/init/ddl.sql
> +    `deleted_at` timestamp NOT NULL COMMENT '削除時刻',
SQL の syntax は大文字/小文字どちらかに統一できたらいいなと思います。

2021-03-26 06:16 UTC, krtsato requested changes

2021-03-26 06:16 UTC, krtsato commented on docker-compose.yml
> +    tty: true
サーバを起動する command がないね。
この yml か Dockerfile にコマンド記述しないと `docker-compose up` 時にサーバ起動してくれないと思います！

2021-03-26 13:49 UTC, hiroki90 commented on server.dockerfile
> +  && curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin \
airは，ファイルの変更を監視し，コンテナ内で起動しているサーバを再起動する目的で取り入れます！
修正しておきます！

2021-03-26 13:50 UTC, hiroki90 commented on db/init/ddl.sql
> +    `deleted_at` timestamp NOT NULL COMMENT '削除時刻',
大文字に統一します！

2021-03-26 15:27 UTC, k-ueki submitted a review, later dismissed
LGTM

2021-03-26 15:27 UTC, krtsato approved these changes

2021-03-26 15:30 UTC, ari1021 commented on db/init/ddl.sql
> +    `name` VARCHAR(64) NOT NULL COMMENT 'ユーザ名',
`name`はログインIDみたいな用途で使うことを想定しているので，uniqueの方がいいかなと思うけどどうかな？

2021-03-26 15:31 UTC, ari1021 commented on db/init/ddl.sql
> +    `deleted_at` TIMESTAMP NOT NULL COMMENT '削除日時',
deleted_atが`not null`だと困る気がする！

2021-03-26 15:33 UTC, ari1021 commented on db/init/ddl.sql
> +    `updated_at` TIMESTAMP NOT NULL COMMENT '更新日時',
タスクを取得するときに，`created_at`(もしくは`updated_at`)でソートするのであれば，index張っておいた方が良さそう？

2021-03-26 15:35 UTC, ari1021 commented on db/init/ddl.sql
> +    `user_id` VARCHAR(128) NOT NULL COMMENT 'ユーザID',
`user_id`は`users`テーブルの`id`をfkにしておく方が良さそう

2021-03-26 15:41 UTC, hiroki90 commented on db/init/ddl.sql
> +    `name` VARCHAR(64) NOT NULL COMMENT 'ユーザ名',
たしかに！uniqueがいいと思う！
追記しときます〜

2021-03-26 15:41 UTC, hiroki90 commented on db/init/ddl.sql
> +    `deleted_at` TIMESTAMP NOT NULL COMMENT '削除日時',
DEFAULT NULLがいいかな！

2021-03-26 16:02 UTC, ari1021 commented
@hiroki90 
パッと見た感じ良さそう！修正ありがとう！  
ちなみにこれってローカル(手元)で動かしてちゃんと動いた？

2021-03-26 16:06 UTC, krtsato commented on docker-compose.yml
> +      MYSQL_DATABASE: hack_ios_server_api
@ari1021 くんが作ってくれた [develop の Dockerfile](https://github.com/CATechAccel/hack-ios-server/blob/develop/Dockerfile) を使うとしたら
docker-compose は以下のようにするかと。

builder 部分を開発用コンテナとして使用
これは林くん・有泉くんで相談する形になるかな。

```yaml
server:
  build:
    context: .
    dockerfile: Dockerfile # develop の Dockerfile
    target: builder # ここで builder を指定
  image: hack-ios-server-img
  container_name: hack-ios-server-cont
  environment:
    MYSQL_USER: root
    MYSQL_ROOT_PASSWORD: "hack-ios-server"
    MYSQL_HOST: mysql
    MYSQL_PORT: 3306
    MYSQL_DATABASE: hack_ios_server_api
  depends_on:
    - mysql
  ports:
    - 9898:8080
  command: sh -c 'air -c ./.air.toml'
  volumes:
    - .:/hack-ios-server
```

2021-03-26 16:16 UTC, hiroki90 commented
> @hiroki90
> パッと見た感じ良さそう！修正ありがとう！
> ちなみにこれってローカル(手元)で動かしてちゃんと動いた？

mockの状態だけど確認して，

- POST /users
- POST /login
のmockレスポンスが返ってくることは確認した！

```
$ curl -X POST -H "Content-Type:application/json" "http://localhost:8080/users" -d '{"name":"hiroki", "password":"passw"}'
{"token":"hirokipassw"}
```
```
$ curl -X POST -H "Content-Type:application/json" "http://localhost:8080/login" -d '{"name":"hiroki", "password":"passw"}'
{"token":"hirokipassw"}

```

2021-03-26 16:26 UTC, ari1021 commented on docker-compose.yml
> +      MYSQL_DATABASE: hack_ios_server_api
airを使ったことないので間違っているかもしれませんが，僕の書いたDockerfileを利用する場合，現状buildする処理が`.air.toml`内に書かれているので，上記のdocker-composeの修正に加えて`.air.toml`を修正する必要とかはありませんか？

2021-03-26 16:29 UTC, ari1021 commented
> > @hiroki90
> > パッと見た感じ良さそう！修正ありがとう！
> > ちなみにこれってローカル(手元)で動かしてちゃんと動いた？
> 
> mockの状態だけど確認して，
> 
> * POST /users
> * POST /login
>   のmockレスポンスが返ってくることは確認した！
> 
> ```
> $ curl -X POST -H "Content-Type:application/json" "http://localhost:8080/users" -d '{"name":"hiroki", "password":"passw"}'
> {"token":"hirokipassw"}
> ```
> 
> ```
> $ curl -X POST -H "Content-Type:application/json" "http://localhost:8080/login" -d '{"name":"hiroki", "password":"passw"}'
> {"token":"hirokipassw"}
> ```

dbは想定通りcreateされてたかな？  
`exec`でコンテナ内に入って
1. テーブルが作られているか
2. `show create table hoge`で，fk制約とかが正しいか

も確認してくれると嬉しいかも！

2021-03-26 17:06 UTC, hiroki90 commented
> dbは想定通りcreateされてたかな？
> `exec`でコンテナ内に入って
> 
> 1. テーブルが作られているか
> 2. `show create table hoge`で，fk制約とかが正しいか
> 
> も確認してくれると嬉しいかも！

1，2とも確認した！いけてると思う！

- `$  show create table tasks;`
- `$  show create table users;`
で確認した結果が以下！

<details> 
  <summary>createされたtasksテーブル</summary> 

```shell
 | tasks | CREATE TABLE `tasks` (
  `id` varchar(128) NOT NULL COMMENT 'タスクID',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新日時',
  `deleted_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '削除日時',
  `name` varchar(64) NOT NULL COMMENT 'タスク名',
  `description` varchar(128) DEFAULT NULL COMMENT 'タスクの詳細',
  `is_done` bit(1) NOT NULL COMMENT 'タスクの状態',
  `user_id` varchar(128) NOT NULL COMMENT 'ユーザID',
  PRIMARY KEY (`id`),
  KEY `idx_created_at` (`created_at`),
  KEY `fk_tasks_user_id` (`user_id`),
  CONSTRAINT `tasks_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='タスク'                                      |
```
</details>


<details>
  <summary>createされたusersテーブル</summary> 

```shell
 | users | CREATE TABLE `users` (
  `id` varchar(128) NOT NULL COMMENT 'ユーザID',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '作成日時',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新日時',
  `deleted_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '削除日時',
  `name` varchar(64) NOT NULL COMMENT 'ユーザ名',
  `password` varchar(128) NOT NULL COMMENT 'パスワード',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ユーザ'                            |
```
</details>


これで大丈夫そうかな？

2021-03-26 17:13 UTC, ari1021 commented
> これで大丈夫そうかな？

`deleted_at`が`not null`になってる気がする！

2021-03-26 18:25 UTC, krtsato commented on docker-compose.yml
> +      MYSQL_DATABASE: hack_ios_server_api
@ari1021 @hiroki90 
結論 .air.toml の変更は要らないです。(動作確認しました)
ただし別の変更点が 2 つあります！

1️⃣  開発環境で使う air, default-mysql-client を [develop の Dockerfile](https://github.com/CATechAccel/hack-ios-server/blob/fbd5e13c2235e37de6cadf4a135abb5b1f8dcd85/Dockerfile#L18-L19) でインストール

- air
  - realize のようなツール
  - 最近もメンテされてるので採用
- default-mysql-client
  - [alpine の mysql-client](https://github.com/CATechAccel/hack-ios-server/blob/3e7675cf8903248fdeacaa0332ecd0550054ab33/server.dockerfile#L9) に相当
  - iOS との共同開発なので, 念の為すべての環境構築をコンテナ化したい背景から採用

<details><summary>Dockerfile 追記内容</summary>

```dockerfile
# Build the binary.

# -
# RUN go build -mod=readonly -v -o server ./cmd/main.go

# +
RUN set -ex && apt-get update && apt-get install --no-install-recommends -y default-mysql-client && \
  apt-get clean && rm -rf /var/lib/apt/lists/* && \
  curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin && \
  go build -mod=readonly -v -o server ./cmd/main.go

## キャッシュ削除については以下を参照
## buster 使ったことないので違ってたらごめん mm
## https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run
```
</details>

2021-03-26 18:54 UTC, krtsato commented on docker-compose.yml
> +      MYSQL_DATABASE: hack_ios_server_api
2️⃣  `WORKDIR` の統一

develop では `/app` になっていました。
本ブランチでは `/hack-ios-server` になっています。
どちらに寄せるかはお任せします。

前者を変える場合, Dockerfile 内の該当箇所を変更します。
`app → hack-ios-server`

後者を変更する場合, docker-compose.yml と server.dockerfile の該当箇所を変更します。
`hack-ios-server → app`  (こちらの方法で動作確認しました)

2021-03-27 00:56 UTC, krtsato commented on docker-compose.yml
> +      MYSQL_DATABASE: hack_ios_server_api
ちょっと説明が回りくどいので改めて
午前中に Slack のスレッドにまとめます。

2021-03-27 06:46 UTC, hiroki90 commented
> `deleted_at`が`not null`になってる気がする！

@ari1021 
ありがとう！nul許可するように直した！
そして相談！

created_atと，updated_at設定は今ので大丈そうかな？
今は
- created_at→デフォルトにCURRENT_TIMESTAMP （作成時のタイムスタンプ）を自動で挿入
- update_at→デフォルトにCURRENT_TIMESTAMP を自動で挿入して，カラムが更新されたら自動でタイムスタンプを更新（ON UPDATE CURRENT_TIMESTAMP）

としてる！

<details> 
  <summary>usersテーブル</summary> 

```shell
$  MySQL [hack_ios_server_api]> show columns from users;
+------------+--------------+------+-----+-------------------+-----------------------------+
| Field      | Type         | Null | Key | Default           | Extra                       |
+------------+--------------+------+-----+-------------------+-----------------------------+
| id         | varchar(128) | NO   | PRI | NULL              |                             |
| created_at | timestamp    | NO   | MUL | CURRENT_TIMESTAMP |                             |
| updated_at | timestamp    | YES  |     | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP |
| deleted_at | timestamp    | YES  |     | NULL              |                             |
| name       | varchar(64)  | NO   | UNI | NULL              |                             |
| password   | varchar(128) | NO   |     | NULL              |                             |
+------------+--------------+------+-----+-------------------+-----------------------------+
6 rows in set (0.001 sec)
```

</details> 

<details> 
  <summary>tasksテーブル</summary> 

```shell
$ MySQL [hack_ios_server_api]> show columns from tasks;
+-------------+--------------+------+-----+-------------------+-----------------------------+
| Field       | Type         | Null | Key | Default           | Extra                       |
+-------------+--------------+------+-----+-------------------+-----------------------------+
| id          | varchar(128) | NO   | PRI | NULL              |                             |
| created_at  | timestamp    | NO   | MUL | CURRENT_TIMESTAMP |                             |
| updated_at  | timestamp    | YES  |     | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP |
| deleted_at  | timestamp    | YES  |     | NULL              |                             |
| name        | varchar(64)  | NO   |     | NULL              |                             |
| description | varchar(128) | YES  |     | NULL              |                             |
| is_done     | bit(1)       | NO   |     | NULL              |                             |
| user_id     | varchar(128) | NO   | MUL | NULL              |                             |
+-------------+--------------+------+-----+-------------------+-----------------------------+
```
</details>

2021-03-27 06:53 UTC, ari1021 commented
> > `deleted_at`が`not null`になってる気がする！
> 
> @ari1021
> ありがとう！nul許可するように直した！
> そして相談！
> 
> created_atと，updated_at設定は今ので大丈そうかな？
> 今は
> 
> * created_at→デフォルトにCURRENT_TIMESTAMP （作成時のタイムスタンプ）を自動で挿入
> * update_at→デフォルトにCURRENT_TIMESTAMP を自動で挿入して，カラムが更新されたら自動でタイムスタンプを更新（ON UPDATE CURRENT_TIMESTAMP）
> 
> としてる！
> 
> usersテーブル
> ```shell
> $  MySQL [hack_ios_server_api]> show columns from users;
> +------------+--------------+------+-----+-------------------+-----------------------------+
> | Field      | Type         | Null | Key | Default           | Extra                       |
> +------------+--------------+------+-----+-------------------+-----------------------------+
> | id         | varchar(128) | NO   | PRI | NULL              |                             |
> | created_at | timestamp    | NO   | MUL | CURRENT_TIMESTAMP |                             |
> | updated_at | timestamp    | YES  |     | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP |
> | deleted_at | timestamp    | YES  |     | NULL              |                             |
> | name       | varchar(64)  | NO   | UNI | NULL              |                             |
> | password   | varchar(128) | NO   |     | NULL              |                             |
> +------------+--------------+------+-----+-------------------+-----------------------------+
> 6 rows in set (0.001 sec)
> ```
> 
> tasksテーブル
> ```shell
> $ MySQL [hack_ios_server_api]> show columns from tasks;
> +-------------+--------------+------+-----+-------------------+-----------------------------+
> | Field       | Type         | Null | Key | Default           | Extra                       |
> +-------------+--------------+------+-----+-------------------+-----------------------------+
> | id          | varchar(128) | NO   | PRI | NULL              |                             |
> | created_at  | timestamp    | NO   | MUL | CURRENT_TIMESTAMP |                             |
> | updated_at  | timestamp    | YES  |     | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP |
> | deleted_at  | timestamp    | YES  |     | NULL              |                             |
> | name        | varchar(64)  | NO   |     | NULL              |                             |
> | description | varchar(128) | YES  |     | NULL              |                             |
> | is_done     | bit(1)       | NO   |     | NULL              |                             |
> | user_id     | varchar(128) | NO   | MUL | NULL              |                             |
> +-------------+--------------+------+-----+-------------------+-----------------------------+
> ```

デフォルト設定はそれで良さそう！  
(gorm使っている場合は，gormでのcrud時に自動でcreated_atとupdated_atをやってくれるみたいだけど，そこは置いといて)  
気になったところとしては，
1. updated_atがnot nullじゃないけど，何か理由ある？
2. mysql側でdefaultの時間設定を入れる場合は，mysqlのtimezoneの設定をmy.cnfに書いておいた方が良さそう？

の2つかな？

2021-03-27 07:13 UTC, hiroki90 commented
> 1. updated_atがnot nullじゃないけど，何か理由ある？

create時にデフォルトでCURRENT_TIMESTAMP を入れないなら，NULLが入ると思って一旦許可にしてた！
CURRENT_TIMESTAMPを入れるなら，not nullにして統一させた方が良いね！not nullに変更する！

2021-03-27 12:40 UTC, hiroki90 commented
> 2. mysql側でdefaultの時間設定を入れる場合は，mysqlのtimezoneの設定をmy.cnfに書いておいた方が良さそう？

色々やってみているんだけど，timezoneの設定がうまくできなかったから一旦後回しにさせてもらう...!

2021-03-27 13:00 UTC, ari1021 approved these changes
https://catechaccel.slack.com/archives/C01Q19DJ89M/p1616814667009200?thread_ts=1616806619.008900&cid=C01Q19DJ89M
あとはこの件を解決してもらえれば良さそう！  
LGTM！

2021-03-27 15:55 UTC, ari1021 commented
moved to https://github.com/CATechAccel/hack-ios-server/pull/15

2021-03-27 15:55 UTC, closed without merging